// Datos de ejemplo para desarrollo (hasta que se conecte Supabase)
import type { Cultivo, Alerta, EstadisticasCultivador, UsuarioFinal, Entrega, Observacion } from "./types/database"

export const mockEstadisticas: EstadisticasCultivador = {
  cultivador_id: "mock-user",
  total_cultivos: 12,
  cultivos_activos: 8,
  cultivos_finalizados: 4,
  alertas_pendientes: 12,
  total_entregas: 45,
  total_gramos_entregados: 3850,
  total_usuarios_finales: 15,
}

export const mockCultivos: Cultivo[] = [
  {
    id: "1",
    cultivador_id: "mock-user",
    nombre: "OG Kush #1",
    variedad: "OG Kush",
    tipo: "hibrida",
    proposito: "medicinal",
    fecha_inicio: "2024-01-15",
    fecha_estimada_cosecha: "2024-05-15",
    estado_actual: "floracion",
    latitud: -34.6037,
    longitud: -58.3816,
    ubicacion_descripcion: "Invernadero Principal",
    metodo_cultivo: "invernadero",
    medio_cultivo: "tierra",
    cantidad_plantas: 4,
    notas: "Primera generación de semillas feminizadas",
    activo: true,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-03-20T15:30:00Z",
  },
  {
    id: "2",
    cultivador_id: "mock-user",
    nombre: "White Widow Medical",
    variedad: "White Widow",
    tipo: "hibrida",
    proposito: "medicinal",
    fecha_inicio: "2024-02-01",
    fecha_estimada_cosecha: "2024-06-01",
    estado_actual: "vegetativo",
    ubicacion_descripcion: "Interior - Sala 2",
    metodo_cultivo: "interior",
    medio_cultivo: "hidroponico",
    cantidad_plantas: 6,
    activo: true,
    created_at: "2024-02-01T09:00:00Z",
    updated_at: "2024-03-18T12:00:00Z",
  },
  {
    id: "3",
    cultivador_id: "mock-user",
    nombre: "Northern Lights Auto",
    variedad: "Northern Lights",
    tipo: "indica",
    proposito: "medicinal",
    fecha_inicio: "2024-03-10",
    fecha_estimada_cosecha: "2024-05-25",
    estado_actual: "floracion",
    ubicacion_descripcion: "Exterior - Sector A",
    metodo_cultivo: "exterior",
    medio_cultivo: "tierra",
    cantidad_plantas: 8,
    activo: true,
    created_at: "2024-03-10T08:00:00Z",
    updated_at: "2024-03-15T14:00:00Z",
  },
  {
    id: "4",
    cultivador_id: "mock-user",
    nombre: "Sour Diesel Terapéutico",
    variedad: "Sour Diesel",
    tipo: "sativa",
    proposito: "medicinal",
    fecha_inicio: "2023-10-15",
    fecha_estimada_cosecha: "2024-02-15",
    estado_actual: "finalizado",
    ubicacion_descripcion: "Invernadero Principal",
    metodo_cultivo: "invernadero",
    medio_cultivo: "tierra",
    cantidad_plantas: 5,
    activo: false,
    created_at: "2023-10-15T10:00:00Z",
    updated_at: "2024-02-20T16:00:00Z",
  },
]

export const mockAlertas: Alerta[] = [
  {
    id: "1",
    cultivo_id: "1",
    tipo: "riego",
    prioridad: "alta",
    titulo: "Verificar nivel de humedad",
    descripcion: "El sustrato puede estar secándose demasiado rápido",
    fecha_programada: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    completada: false,
    recordatorio_dias_antes: 0,
    recurrente: true,
    intervalo_dias: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    cultivo_id: "1",
    tipo: "nutricion",
    prioridad: "media",
    titulo: "Aplicar nutrientes de floración",
    descripcion: "Aumentar fósforo y potasio para desarrollo de flores",
    fecha_programada: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    completada: false,
    recordatorio_dias_antes: 1,
    recurrente: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    cultivo_id: "2",
    tipo: "poda",
    prioridad: "alta",
    titulo: "Poda apical (topping)",
    descripcion: "Realizar corte en el nudo principal para promover ramificación",
    fecha_programada: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    completada: false,
    recordatorio_dias_antes: 1,
    recurrente: false,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    cultivo_id: "3",
    tipo: "control_plagas",
    prioridad: "urgente",
    titulo: "Inspección de plagas",
    descripcion: "Se detectaron signos de trips, revisar urgentemente",
    fecha_programada: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    completada: false,
    recordatorio_dias_antes: 0,
    recurrente: false,
    created_at: new Date().toISOString(),
  },
]

export const mockUsuariosFinales: UsuarioFinal[] = [
  {
    id: "1",
    cultivador_id: "mock-user",
    nombre_completo: "María González",
    documento: "12345678",
    telefono: "+54 11 1234-5678",
    email: "maria.gonzalez@email.com",
    condicion_medica: "Dolor crónico - Artritis reumatoide",
    dosis_recomendada: "0.5ml de aceite 2 veces al día",
    notas: "Paciente con buena respuesta al tratamiento. Prefiere aceite sublingual.",
    activo: true,
    fecha_registro: "2023-06-15T10:00:00Z",
  },
  {
    id: "2",
    cultivador_id: "mock-user",
    nombre_completo: "Juan Pérez",
    documento: "23456789",
    telefono: "+54 11 2345-6789",
    email: "juan.perez@email.com",
    condicion_medica: "Insomnio crónico y ansiedad",
    dosis_recomendada: "1g de flor por la noche",
    notas: "Requiere seguimiento mensual. Buena adherencia al tratamiento.",
    activo: true,
    fecha_registro: "2023-08-20T14:30:00Z",
  },
  {
    id: "3",
    cultivador_id: "mock-user",
    nombre_completo: "Ana Martínez",
    documento: "34567890",
    telefono: "+54 11 3456-7890",
    email: "ana.martinez@email.com",
    condicion_medica: "Epilepsia focal",
    dosis_recomendada: "1ml de aceite CBD 3 veces al día",
    notas: "Paciente bajo control neurológico. Requiere alta concentración de CBD.",
    activo: true,
    fecha_registro: "2023-09-10T09:15:00Z",
  },
]

export const mockEntregas: Entrega[] = [
  {
    id: "1",
    cultivo_id: "4",
    usuario_final_id: "1",
    cultivador_id: "mock-user",
    fecha_entrega: "2024-02-25T16:00:00Z",
    cantidad_gramos: 50,
    tipo_producto: "aceite" as const,
    lote: "LOTE-2024-002",
    notas: "Entrega mensual regular. Paciente reporta mejora en síntomas.",
    created_at: "2024-02-25T16:00:00Z",
  },
  {
    id: "2",
    cultivo_id: "4",
    usuario_final_id: "2",
    cultivador_id: "mock-user",
    fecha_entrega: "2024-02-20T14:30:00Z",
    cantidad_gramos: 120,
    tipo_producto: "flor" as const,
    lote: "LOTE-2024-001",
    notas: "Primera entrega del nuevo lote. Paciente satisfecho con calidad.",
    created_at: "2024-02-20T14:30:00Z",
  },
  {
    id: "3",
    cultivo_id: "4",
    usuario_final_id: "3",
    cultivador_id: "mock-user",
    fecha_entrega: "2024-02-18T11:00:00Z",
    cantidad_gramos: 30,
    tipo_producto: "aceite" as const,
    lote: "LOTE-2024-002",
    notas: "Aceite con alto contenido de CBD. Control de calidad aprobado.",
    created_at: "2024-02-18T11:00:00Z",
  },
]

// Datos para gráficos
export const cultivosPorEtapa = [
  { etapa: "Germinación", cantidad: 2 },
  { etapa: "Vegetativo", cantidad: 3 },
  { etapa: "Floración", cantidad: 3 },
  { etapa: "Cosecha", cantidad: 0 },
  { etapa: "Secado", cantidad: 0 },
]

export const entregasPorMes = [
  { mes: "Oct", cantidad: 8, gramos: 650 },
  { mes: "Nov", cantidad: 10, gramos: 820 },
  { mes: "Dic", cantidad: 12, gramos: 980 },
  { mes: "Ene", cantidad: 7, gramos: 560 },
  { mes: "Feb", cantidad: 8, gramos: 840 },
]

export const tiempoPromedioPorEtapa = [
  { etapa: "Germinación", dias: 7 },
  { etapa: "Vegetativo", dias: 35 },
  { etapa: "Floración", dias: 56 },
  { etapa: "Secado", dias: 14 },
  { etapa: "Curado", dias: 21 },
]

export const alertasPorTipo = [
  { tipo: "Riego", cantidad: 4 },
  { tipo: "Nutrición", cantidad: 3 },
  { tipo: "Poda", cantidad: 2 },
  { tipo: "Control plagas", cantidad: 2 },
  { tipo: "Otros", cantidad: 1 },
]

export const mockObservaciones: Observacion[] = [
  {
    id: "obs-1",
    cultivo_id: "1",
    cultivador_id: "mock-user",
    fecha: "2024-03-15T10:00:00Z",
    descripcion: "Plantas respondiendo bien al cambio de fotoperiodo. Primera semana de floración.",
    altura_cm: 45.5,
    ph: 6.2,
    temperatura_celsius: 24.0,
    humedad_porcentaje: 55.0,
    foto_url: "/cannabis-plant-flowering.jpg",
  },
  {
    id: "obs-2",
    cultivo_id: "1",
    cultivador_id: "mock-user",
    fecha: "2024-03-10T14:30:00Z",
    descripcion: "Transición exitosa a fase de floración. Se observan primeros pistilos.",
    altura_cm: 42.0,
    ph: 6.3,
    temperatura_celsius: 23.5,
    humedad_porcentaje: 58.0,
    foto_url: "/cannabis-plant-early-flowering-pistils.jpg",
  },
  {
    id: "obs-3",
    cultivo_id: "1",
    cultivador_id: "mock-user",
    fecha: "2024-03-05T09:15:00Z",
    descripcion: "Último día de etapa vegetativa. Plantas con estructura robusta y saludable.",
    altura_cm: 38.0,
    ph: 6.4,
    temperatura_celsius: 25.0,
    humedad_porcentaje: 60.0,
  },
  {
    id: "obs-4",
    cultivo_id: "2",
    cultivador_id: "mock-user",
    fecha: "2024-03-18T11:00:00Z",
    descripcion: "Crecimiento vegetativo óptimo. Sistema hidropónico funcionando correctamente.",
    altura_cm: 32.5,
    ph: 5.8,
    temperatura_celsius: 22.0,
    humedad_porcentaje: 65.0,
    foto_url: "/cannabis-plant-vegetative-growth-hydroponic.jpg",
  },
  {
    id: "obs-5",
    cultivo_id: "3",
    cultivador_id: "mock-user",
    fecha: "2024-03-20T16:45:00Z",
    descripcion: "Desarrollo de cogollos avanzado. Resina visible en tricomas.",
    altura_cm: 68.0,
    ph: 6.5,
    temperatura_celsius: 21.0,
    humedad_porcentaje: 50.0,
    foto_url: "/cannabis-buds-with-trichomes.jpg",
  },
]
